# Generated by Django 3.2 on 2021-05-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_type',
            old_name='name',
            new_name='label',
        ),
    ]
