# Generated by Django 3.2 on 2021-05-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_rename_name_game_type_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='gamer_type_id',
            new_name='game_type_id',
        ),
    ]
